import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from "next/link"
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <nav>
        <ul className="flex flex-row justify-between w-14">
          <li>
            <Link href="/showcase">Showcase</Link>
          </li>
          <li>
            <Link href="/about">About</Link>
            </li>
        </ul>
      </nav>
        {children}
        </body>
    </html>
  )
}
